name: biogas_technician_app
version: 1.0.0+1
publish_to: none
description: A biogas technician service booking and repair app.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons:
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.1.2
  rename_app: ^1.3.0
  flutter_svg: ^2.0.9
  carousel_slider: ^5.1.1
  badges: ^3.1.2
  flutter_animate: ^4.2.1
  google_sign_in: ^6.1.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.7.3
  firebase_database: ^10.4.0

  flutter: 
    sdk: flutter

dev_dependencies:
  mockito:
  flutter_lints:

  integration_test:
    sdk: flutter

  flutter_test: 
    sdk: flutter

dependency_overrides:
  firebase_auth_web: ^5.8.12
  firebase_core_platform_interface: ^5.0.0
  file: ^6.1.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/latest_app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/latest_app_icon_foreground.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900

